-- Idempotent creation. Handle ORA-00955 (name exists) and ORA-01408 (duplicate index columns).
DECLARE
  e_exists EXCEPTION; PRAGMA EXCEPTION_INIT(e_exists, -955);
  e_dupcols EXCEPTION; PRAGMA EXCEPTION_INIT(e_dupcols, -1408);
BEGIN
  -- email_bounces
  BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE email_bounces (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id NUMBER NOT NULL, campaign_id NUMBER, email VARCHAR2(320) NOT NULL, bounce_type VARCHAR2(50), reason VARCHAR2(4000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)';
  EXCEPTION WHEN e_exists THEN NULL; END;
  BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_bounce_user_email ON email_bounces(user_id,email)';
  EXCEPTION
    WHEN e_exists THEN NULL;
    WHEN e_dupcols THEN NULL;
  END;

  -- email_complaints
  BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE email_complaints (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id NUMBER NOT NULL, campaign_id NUMBER, email VARCHAR2(320) NOT NULL, source VARCHAR2(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)';
  EXCEPTION WHEN e_exists THEN NULL; END;
  BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_complaint_user_email ON email_complaints(user_id,email)';
  EXCEPTION
    WHEN e_exists THEN NULL;
    WHEN e_dupcols THEN NULL;
  END;

  -- suppression_list (UNIQUE constraint auto-creates supporting index so skip manual duplicate index)
  BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE suppression_list (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id NUMBER NOT NULL, email VARCHAR2(320) NOT NULL, reason VARCHAR2(200), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE (user_id,email))';
  EXCEPTION WHEN e_exists THEN NULL; END;
END;
/
