-- Audit log for admin backfill triggers
DECLARE
    col_exists NUMBER;
BEGIN
    BEGIN
        SELECT 1 INTO col_exists FROM user_tab_columns WHERE table_name='USERS' AND column_name='IS_ADMIN';
    EXCEPTION WHEN NO_DATA_FOUND THEN
        EXECUTE IMMEDIATE 'ALTER TABLE users ADD (is_admin NUMBER(1) DEFAULT 0)';
    END;
END;
/

CREATE TABLE admin_backfill_audit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    triggered_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    admin_username VARCHAR2(150),
    user_id NUMBER NOT NULL,
    start_instant TIMESTAMP NOT NULL,
    end_instant TIMESTAMP NOT NULL,
    window_hours NUMBER,
    status VARCHAR2(40) DEFAULT 'STARTED',
    message VARCHAR2(4000)
);
CREATE INDEX idx_admin_backfill_user_time ON admin_backfill_audit(user_id, triggered_at);

-- Add admin role flag if not already (idempotent)
-- Ensure defaults set (idempotent)
UPDATE users SET is_admin=NVL(is_admin,0);