-- Core auth + subscription tables (Oracle dialect)
CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(100) NOT NULL,
        password VARCHAR2(255) NOT NULL,
        email VARCHAR2(150) NOT NULL,
        first_name VARCHAR2(100),
        last_name VARCHAR2(100),
        currency VARCHAR2(8) DEFAULT 'USD' NOT NULL,
        locale VARCHAR2(16) DEFAULT 'en-US' NOT NULL,
        CONSTRAINT uq_users_username UNIQUE(username),
        CONSTRAINT uq_users_email UNIQUE(email)
);

CREATE TABLE plans (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plan_type VARCHAR2(32) NOT NULL,
        region VARCHAR2(16) NOT NULL,
        currency VARCHAR2(8) NOT NULL,
        billing_period VARCHAR2(16) NOT NULL,
        amount NUMBER NOT NULL,
        statements_per_month NUMBER,
        pages_per_statement NUMBER,
        features CLOB,
        combined_bank NUMBER,
        CONSTRAINT uq_plan UNIQUE (plan_type, region, billing_period)
);

CREATE TABLE subscriptions (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plan_type VARCHAR2(32),
        start_date TIMESTAMP,
        end_date TIMESTAMP,
        status VARCHAR2(32),
        external_payment_id VARCHAR2(128),
        external_order_id VARCHAR2(128),
        billing_period VARCHAR2(16),
        user_id NUMBER UNIQUE,
        CONSTRAINT fk_sub_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Seed example plans (guarded inserts to avoid duplicates if rerun in dev)
INSERT INTO plans (plan_type, region, currency, billing_period, amount, statements_per_month, pages_per_statement, features)
SELECT 'FREE','GLOBAL','USD','MONTHLY',0,3,10,'basic' FROM dual WHERE NOT EXISTS (
    SELECT 1 FROM plans WHERE plan_type='FREE' AND region='GLOBAL' AND billing_period='MONTHLY'
);
INSERT INTO plans (plan_type, region, currency, billing_period, amount, statements_per_month, pages_per_statement, features)
SELECT 'PRO','GLOBAL','USD','MONTHLY',999,5,50,'advanced,analytics' FROM dual WHERE NOT EXISTS (
    SELECT 1 FROM plans WHERE plan_type='PRO' AND region='GLOBAL' AND billing_period='MONTHLY'
);
INSERT INTO plans (plan_type, region, currency, billing_period, amount, statements_per_month, pages_per_statement, features)
SELECT 'PRO','GLOBAL','USD','YEARLY',9990,5,50,'advanced,analytics' FROM dual WHERE NOT EXISTS (
    SELECT 1 FROM plans WHERE plan_type='PRO' AND region='GLOBAL' AND billing_period='YEARLY'
);
INSERT INTO plans (plan_type, region, currency, billing_period, amount, statements_per_month, pages_per_statement, features)
SELECT 'PREMIUM','GLOBAL','USD','MONTHLY',1999,100,100,'all' FROM dual WHERE NOT EXISTS (
    SELECT 1 FROM plans WHERE plan_type='PREMIUM' AND region='GLOBAL' AND billing_period='MONTHLY'
);
INSERT INTO plans (plan_type, region, currency, billing_period, amount, statements_per_month, pages_per_statement, features)
SELECT 'PREMIUM','GLOBAL','USD','YEARLY',19990,100,100,'all' FROM dual WHERE NOT EXISTS (
    SELECT 1 FROM plans WHERE plan_type='PREMIUM' AND region='GLOBAL' AND billing_period='YEARLY'
);
