-- Add ORG_ID columns for org-wide aggregation
ALTER TABLE CAMPAIGN_COSTS ADD (ORG_ID NUMBER);
ALTER TABLE COST_ALLOCATIONS ADD (ORG_ID NUMBER);
ALTER TABLE ROI_GOALS ADD (ORG_ID NUMBER);

-- Optional aggregated daily cost MV (can be fast refreshed later)
CREATE TABLE COST_DAILY_AGG (
    ORG_ID NUMBER,
    COST_DATE DATE NOT NULL,
    TOTAL_COST NUMBER(18,4) NOT NULL,
    BASE_CURRENCY VARCHAR2(10) NOT NULL,
    PRIMARY KEY(ORG_ID, COST_DATE)
);

CREATE INDEX IDX_CAMPAIGN_COSTS_ORG_DATE ON CAMPAIGN_COSTS (ORG_ID, COST_DATE);
CREATE INDEX IDX_COST_ALLOC_ORG_PERIOD ON COST_ALLOCATIONS (ORG_ID, PERIOD_START, PERIOD_END);
