-- Oracle compatible DDL (adjust datatypes as needed) for new email marketing domain tables
CREATE TABLE contacts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    email VARCHAR2(320) NOT NULL,
    first_name VARCHAR2(100),
    last_name VARCHAR2(100),
    segment VARCHAR2(64),
    unsubscribed NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_contact_user_email UNIQUE (user_id, email)
);
CREATE INDEX idx_contacts_user ON contacts(user_id);
CREATE INDEX idx_contacts_email ON contacts(email);

CREATE TABLE email_templates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(150) NOT NULL,
    html CLOB NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_template_user ON email_templates(user_id);

CREATE TABLE campaigns (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(150) NOT NULL,
    segment VARCHAR2(64),
    template_id NUMBER,
    status VARCHAR2(32) DEFAULT 'DRAFT',
    scheduled_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_recipients NUMBER DEFAULT 0,
    sent_count NUMBER DEFAULT 0,
    open_count NUMBER DEFAULT 0,
    click_count NUMBER DEFAULT 0
);
CREATE INDEX idx_campaign_user ON campaigns(user_id);

CREATE TABLE email_queue (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id NUMBER,
    user_id NUMBER,
    recipient VARCHAR2(320),
    subject VARCHAR2(255),
    body CLOB,
    status VARCHAR2(16) DEFAULT 'PENDING',
    attempt NUMBER DEFAULT 0,
    next_attempt_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_queue_status ON email_queue(status);
CREATE INDEX idx_queue_campaign ON email_queue(campaign_id);
