-- Flyway migration V32: Import staging table for bulk imports

CREATE TABLE import_staging (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id NUMBER NOT NULL,
  row_number NUMBER,
  raw_data CLOB,
  parsed_email VARCHAR2(320),
  parsed_first_name VARCHAR2(200),
  parsed_last_name VARCHAR2(200),
  status VARCHAR2(50) DEFAULT 'PENDING',
  error_message VARCHAR2(4000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_import_staging_job ON import_staging(job_id);
