-- Flyway migration V41: Template variable bindings
-- Maps template variables to data sources (contact columns, custom fields, static values, or system-computed)

BEGIN
  -- TABLE: TEMPLATE_VARIABLE_BINDINGS
  BEGIN EXECUTE IMMEDIATE q'[CREATE TABLE template_variable_bindings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id NUMBER NOT NULL,
    var_name VARCHAR2(200) NOT NULL,
    source_type VARCHAR2(50) NOT NULL, -- CONTACT_COLUMN | CUSTOM_FIELD | STATIC | SYSTEM
    source_key VARCHAR2(255),          -- e.g., first_name, custom:loyalty_tier, or system key
    default_value VARCHAR2(4000),
    transform_json CLOB,               -- optional JSON for transformations/formatting rules
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
  )]'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;

  -- Uniqueness per template + var name
  BEGIN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_tvb_template_var ON template_variable_bindings(template_id, var_name)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF; END;

  -- Indexes for lookup by template and type
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_tvb_template ON template_variable_bindings(template_id)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF; END;
  BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_tvb_source ON template_variable_bindings(source_type, source_key)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF; END;

  -- Foreign key (best-effort, ignore if fails due to prior state)
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE template_variable_bindings ADD CONSTRAINT fk_tvb_template FOREIGN KEY (template_id) REFERENCES email_templates(id)'; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
