CREATE TABLE unsubscribe_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    campaign_id BIGINT NULL,
    email VARCHAR(320) NOT NULL,
    reason VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_unsub_user_campaign ON unsubscribe_events(user_id, campaign_id);
CREATE INDEX idx_unsub_user_email ON unsubscribe_events(user_id, email);