-- Oracle table for email events; consider interval partitioning by day for performance
CREATE TABLE email_events (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER(19) NOT NULL,
  campaign_id NUMBER(19) NOT NULL,
  event_type VARCHAR2(32) NOT NULL,
  event_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  meta CLOB
);
CREATE INDEX idx_ev_user ON email_events(user_id);
CREATE INDEX idx_ev_campaign ON email_events(campaign_id);
CREATE INDEX idx_ev_type ON email_events(event_type);
-- Optional: ALTER TABLE email_events PARTITION BY RANGE (event_time) INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) (PARTITION p0 VALUES LESS THAN (TO_DATE('2025-01-01','YYYY-MM-DD')));