-- Template management extension
CREATE TABLE template_categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    slug VARCHAR2(120) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_category_user_slug UNIQUE(user_id, slug)
);
CREATE INDEX idx_category_user ON template_categories(user_id);

ALTER TABLE email_templates ADD (category_id NUMBER, description VARCHAR2(400), tags VARCHAR2(400));
ALTER TABLE email_templates ADD (is_shared NUMBER(1) DEFAULT 0 NOT NULL, base_template_id NUMBER);

CREATE TABLE template_versions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id NUMBER NOT NULL,
    version_number NUMBER NOT NULL,
    html CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR2(150),
    CONSTRAINT uq_template_version UNIQUE(template_id, version_number)
);
CREATE INDEX idx_template_versions_template ON template_versions(template_id);

CREATE TABLE template_variables (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id NUMBER NOT NULL,
    var_name VARCHAR2(100) NOT NULL,
    default_value VARCHAR2(4000),
    description VARCHAR2(400),
    required NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT uq_template_var UNIQUE(template_id, var_name)
);
CREATE INDEX idx_template_variables_template ON template_variables(template_id);

CREATE TABLE template_assets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id NUMBER NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    content_type VARCHAR2(120),
    storage_key VARCHAR2(500) NOT NULL,
    size_bytes NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_template_assets_template ON template_assets(template_id);

-- Basic performance tracking placeholder
CREATE TABLE template_performance (
    template_id NUMBER PRIMARY KEY,
    total_sends NUMBER DEFAULT 0,
    total_opens NUMBER DEFAULT 0,
    total_clicks NUMBER DEFAULT 0,
    last_used_at TIMESTAMP
);

-- Grant future: Add foreign keys (omitted now to keep lightweight for tests) */