spring:
  application:
    name: email-marketing-api
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${DB_USER:APP}
    password: ${DB_PASSWORD:APP}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        # Oracle optimizer hints or batch settings
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 50
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  baseline-on-migrate: true
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:25}
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true

security:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_SUPER_LONG_SECRET_CHANGE_ME_SUPER_LONG_SECRET}

app:
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
  subscription:
    default:
      currency: USD
      free-plan: FREE
  email:
    from-address: ${EMAIL_FROM:no-reply@yourdomain.com}
    queue:
      max-retries: 3
      retry-delay-seconds: 120

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
