spring:
  application:
    name: email-marketing-backend
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${DB_USER:APP}
    password: ${DB_PASSWORD:APP}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
        # Oracle optimizer hints or batch settings
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 50
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  baseline-on-migrate: true
  mail:
    # OCI Email Delivery SMTP (override via env vars in production)
    host: ${SMTP_HOST:smtp.email.${OCI_REGION:ap-hyderabad-1}.oci.oraclecloud.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:ocid1.user.oc1..aaaaaaaa544nuaarbgcp3jojdmtugvy7x5uztswtrk2yko36ubhdpcf6ph3q@ocid1.tenancy.oc1..aaaaaaaabui5ysesbenyvlhqdcrhyla3elkbz2hvfjmxtzut724knwsgfmza.ht.com}        # OCI SMTP credential user (ocid or generated username)
    password: dg{2kBArnGHx(ZL2Uz(1      # OCI SMTP credential password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

oracle:
  email:
    delivery:
      enabled: ${OCI_EMAIL_ENABLED:true}
      sender: ${OCI_EMAIL_SENDER:support@resumeneuron.com}   # Verified sender address/domain in OCI
      region: ${OCI_REGION:ap-hyderabad-1}                 # Region for instrumentation header

security:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_SUPER_LONG_SECRET_CHANGE_ME_SUPER_LONG_SECRET}

rateLimiter:
  adminBackfill:
    capacity: 5
    refillSeconds: 300

admin:
  audit:
    enabled: true

forecast:
  hw:
    alpha: 0.3
    beta: 0.05
    gamma: 0.2

alerts:
  thresholds:
    open-rate-min: 0.15
  resilience4j:
    circuitbreaker:
      instances:
        exchangeRateApi:
          failure-rate-threshold: 50
          sliding-window-size: 20
          wait-duration-in-open-state: 30s
          permitted-number-of-calls-in-half-open-state: 3
        benchmarkApi:
          failure-rate-threshold: 40
          sliding-window-size: 10
          wait-duration-in-open-state: 60s
    retry:
      instances:
        exchangeRateApi:
          max-attempts: 3
          wait-duration: 500ms
        benchmarkApi:
          max-attempts: 4
          wait-duration: 1s
        dbInsertTransient:
          max-attempts: 3
          wait-duration: 200ms
    open-rate-drop-pct: 20   # percent drop vs baseline
    click-rate-drop-pct: 25  # percent drop vs baseline
    conversion-spike-pct: 50 # percent spike vs baseline

timeseries:
  mv:
    refresh-ms: 300000
  cache:
    warm:
      campaign-ids: ""   # comma separated list, empty means skip campaign warming

app:
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
  subscription:
    default:
      currency: USD
      free-plan: FREE
finance:
  base-currency: USD
  email:
    from-address: ${EMAIL_FROM:no-reply@yourdomain.com}
    queue:
      max-retries: 3
      retry-delay-seconds: 120
assets:
  read-url-default-expiry-minutes: 43200

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

ai:
  python:
    base-url: ${PY_AI_BASE_URL:http://localhost:8000}

  assets:
    read-url-default-expiry-minutes: 43200
